### PR TITLE
Update panhunt.py

### PR DESCRIPTION
**Pull request by godjil**
Remove mask in final report

### CODE REVIEW

**Comment by godjil** [comment]
ADD linux gzip support

**Comment by godjil** [comment]
please add gzip support

**Comment by godjil** [comment]
Traceback (most recent call last):                                                                                                                           | ETA:  2:15:35 PANs:0
  File "panhunt.py", line 251, in <module>
    total_files_searched, pans_found, all_files = hunt_pans()
  File "panhunt.py", line 196, in hunt_pans
    total_docs, doc_pans_found = filehunt.find_all_regexs_in_files([afile for afile in all_files if not afile.errors and afile.type in ('TEXT','ZIP','SPECIAL')], pan_regexs, search_extensions, 'PAN', gauge_update_function)
  File "/home/kochetkov/PANhunt-master/filehunt.py", line 326, in find_all_regexs_in_files
    matches = afile.check_regexs(regexs, search_extensions)
  File "/home/kochetkov/PANhunt-master/filehunt.py", line 100, in check_regexs
    except WindowsError:
NameError: global name 'WindowsError' is not defined

**Comment by bli-dn** [comment]
These are two separate issues to the initial rejected pull request, please create separate issues. The WindowsError you may be able to fix by changing to OSError, test and create a separate pull request.

**Pull request closed without merging**
